import { Check, ArrowDownRight, Printer, Boxes, Banknote } from 'lucide-react';
import FeatureOverview from './FeatureOverview';
import { getStorefront } from '@/data/storefront';
import type { Locale } from '@/data/localized';

export default function ShopFeatures({ locale }: { locale: Locale }) {
  const copy = getStorefront(locale);
  const icons = [Printer, Boxes, Banknote];
  return <section id="features" className="shop-section shop-features"><div className="shop-section-heading"><p className="shop-eyebrow">01 / LOKA KASIR</p><h2>{copy.featureTitle}<br /><span>{copy.featureLead}</span></h2></div><div className="shop-feature-grid">{copy.features.map((feature, i) => { const Icon = icons[i]; return <article className={`shop-feature feature-${i}`} key={feature.title}><div className="feature-visual"><div className="feature-visual-label"><span>{feature.label}</span><Icon size={15} /></div>{i === 0 ? <div className="paper-receipt"><strong>KEDAI LOKA</strong><span>#001 · TAKE AWAY</span><div><span>1 × {copy.products[0]}</span><span>18.000</span></div><div><span>1 × {copy.products[4]}</span><span>12.000</span></div><div className="paper-total"><span>{copy.total}</span><b>Rp30.000</b></div><p><Check size={12} />{copy.paid}</p><div className="receipt-barcode" aria-hidden="true" /></div> : i === 1 ? <div className="stock-sheet">{copy.stock.map((name, index) => <div key={name}><div><span>{name}</span><strong>{[42, 28, 4][index]} <small>{copy.stockUnit}</small></strong></div><span className={`stock-bar ${index === 2 ? 'low' : ''}`}><i style={{width: `${[76, 51, 13][index]}%`}} /></span></div>)}<p><span />{copy.stockLow}</p></div> : <div className="shift-sheet"><span>SHIFT / 01</span><div><span>{copy.cash}</span><strong>Rp450.000</strong></div><div><span>{copy.counted}</span><strong>Rp450.000</strong></div><div className="shift-total"><span>{copy.balance}</span><strong>Rp0</strong></div><p><Check size={15} />{copy.balanced}</p></div>}<span className="feature-example">{copy.illustrative}</span></div><div className="feature-text"><span className="feature-index">0{i+1}</span><div><h3>{feature.title}</h3><p>{feature.desc}</p></div></div></article>; })}</div><details className="shop-feature-details"><summary>{copy.featureMore}<ArrowDownRight size={18} /></summary><FeatureOverview locale={locale} /></details></section>;
}
